package main

const decimalExpectFormat = "%d != %d"
const dummyFileName = "test.txt"
const errorExpectFormat = "%s != %s"
const fixedDateString = "2006/01/02"
const fixedDateTimeString = "2015-10-01 00:00:00"
const fixedTimeString = "2006-01-02 15:04:05"
const floatExpectFormat = "%f != %f"
const helloWorld = "Hello, World!"
const isDirFormat = "isdir = %v\n"
const logNumberFormat = "ログの%d行目\n"
const nameFormat = "name = %s\n"
const sizeFormat = "size = %d\n"
const stringExpectFormat = "%s != %s"
const valueExpectFormat = "%v != %v"
const valueTypeFormat = "%v %T\n"
