name: Go Package

on:
  push:
    branches: [develop, main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./zoo

    steps:
      - uses: Kesin11/actions-timeline@v2
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          show-waiting-runner: true
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v2
        with:
          version: 2025.8.21
          install: true
          cache: true
      - run: |
          mise run setup
          mise run build
          mise run test
          mise run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
