name: Go Package

on:
  push:
    branches: [develop, main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zoo

    steps:
      - uses: actions/checkout@v3
      - name: Go Package
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build
        run: go build -o zoo
      - name: Test
        run: go test -v ./...
      - name: Run Coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
