name: Monthly Branch and PR Creation

on:
  push:
  # schedule:
    # - cron: '0 0 1 * *'  # 毎月1日の0時0分実行

permissions:
  contents: write
  pull-requests: write

jobs:
  create_branch_and_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Create new branch
        id: create-branch
        run: |
          BRANCH_NAME=$(date +'%Y%m%d')_main
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
          git fetch origin --prune
          git checkout develop
          git pull origin develop
          git switch -c $BRANCH_NAME
          git merge origin/main
          git push origin $BRANCH_NAME -f

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ env.branch_name }}
          title: ${{ env.branch_name }} to develop
          body: 'Automated PR from ${{ env.branch_name }} to develop'
